/* Auto-generated by genmsg_cpp for file /opt/ros/hydro/stacks/qbo_object_recognition/srv/LearnNewObject.srv */
#ifndef QBO_OBJECT_RECOGNITION_SERVICE_LEARNNEWOBJECT_H
#define QBO_OBJECT_RECOGNITION_SERVICE_LEARNNEWOBJECT_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace qbo_object_recognition
{
template <class ContainerAllocator>
struct LearnNewObjectRequest_ {
  typedef LearnNewObjectRequest_<ContainerAllocator> Type;

  LearnNewObjectRequest_()
  : object_name()
  {
  }

  LearnNewObjectRequest_(const ContainerAllocator& _alloc)
  : object_name(_alloc)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _object_name_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  object_name;


  typedef boost::shared_ptr< ::qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LearnNewObjectRequest
typedef  ::qbo_object_recognition::LearnNewObjectRequest_<std::allocator<void> > LearnNewObjectRequest;

typedef boost::shared_ptr< ::qbo_object_recognition::LearnNewObjectRequest> LearnNewObjectRequestPtr;
typedef boost::shared_ptr< ::qbo_object_recognition::LearnNewObjectRequest const> LearnNewObjectRequestConstPtr;



template <class ContainerAllocator>
struct LearnNewObjectResponse_ {
  typedef LearnNewObjectResponse_<ContainerAllocator> Type;

  LearnNewObjectResponse_()
  : learned(false)
  {
  }

  LearnNewObjectResponse_(const ContainerAllocator& _alloc)
  : learned(false)
  {
  }

  typedef uint8_t _learned_type;
  uint8_t learned;


  typedef boost::shared_ptr< ::qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct LearnNewObjectResponse
typedef  ::qbo_object_recognition::LearnNewObjectResponse_<std::allocator<void> > LearnNewObjectResponse;

typedef boost::shared_ptr< ::qbo_object_recognition::LearnNewObjectResponse> LearnNewObjectResponsePtr;
typedef boost::shared_ptr< ::qbo_object_recognition::LearnNewObjectResponse const> LearnNewObjectResponseConstPtr;


struct LearnNewObject
{

typedef LearnNewObjectRequest Request;
typedef LearnNewObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct LearnNewObject
} // namespace qbo_object_recognition

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "2f12226348d323c2e5b2031b3da53f1b";
  }

  static const char* value(const  ::qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x2f12226348d323c2ULL;
  static const uint64_t static_value2 = 0xe5b2031b3da53f1bULL;
};

template<class ContainerAllocator>
struct DataType< ::qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "qbo_object_recognition/LearnNewObjectRequest";
  }

  static const char* value(const  ::qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
\n\
string object_name\n\
\n\
";
  }

  static const char* value(const  ::qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "c9e56102f89a9558f44983cd3c0495b4";
  }

  static const char* value(const  ::qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xc9e56102f89a9558ULL;
  static const uint64_t static_value2 = 0xf44983cd3c0495b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "qbo_object_recognition/LearnNewObjectResponse";
  }

  static const char* value(const  ::qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool learned\n\
\n\
\n\
";
  }

  static const char* value(const  ::qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.object_name);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LearnNewObjectRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.learned);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct LearnNewObjectResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<qbo_object_recognition::LearnNewObject> {
  static const char* value() 
  {
    return "806e4614bcce891ffdc0106c00889221";
  }

  static const char* value(const qbo_object_recognition::LearnNewObject&) { return value(); } 
};

template<>
struct DataType<qbo_object_recognition::LearnNewObject> {
  static const char* value() 
  {
    return "qbo_object_recognition/LearnNewObject";
  }

  static const char* value(const qbo_object_recognition::LearnNewObject&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "806e4614bcce891ffdc0106c00889221";
  }

  static const char* value(const qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "qbo_object_recognition/LearnNewObject";
  }

  static const char* value(const qbo_object_recognition::LearnNewObjectRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "806e4614bcce891ffdc0106c00889221";
  }

  static const char* value(const qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "qbo_object_recognition/LearnNewObject";
  }

  static const char* value(const qbo_object_recognition::LearnNewObjectResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // QBO_OBJECT_RECOGNITION_SERVICE_LEARNNEWOBJECT_H

