(cl:defpackage qbo_arduqbo-srv
  (:use )
  (:export
   "BASESTOP"
   "<BASESTOP-REQUEST>"
   "BASESTOP-REQUEST"
   "<BASESTOP-RESPONSE>"
   "BASESTOP-RESPONSE"
   "TEST"
   "<TEST-REQUEST>"
   "TEST-REQUEST"
   "<TEST-RESPONSE>"
   "TEST-RESPONSE"
   "TORQUEENABLE"
   "<TORQUEENABLE-REQUEST>"
   "TORQUEENABLE-REQUEST"
   "<TORQUEENABLE-RESPONSE>"
   "TORQUEENABLE-RESPONSE"
  ))

