/* Auto-generated by genmsg_cpp for file /opt/ros/hydro/stacks/qbo_arduqbo/srv/BaseStop.srv */
#ifndef QBO_ARDUQBO_SERVICE_BASESTOP_H
#define QBO_ARDUQBO_SERVICE_BASESTOP_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace qbo_arduqbo
{
template <class ContainerAllocator>
struct BaseStopRequest_ {
  typedef BaseStopRequest_<ContainerAllocator> Type;

  BaseStopRequest_()
  : sender()
  , state(false)
  {
  }

  BaseStopRequest_(const ContainerAllocator& _alloc)
  : sender(_alloc)
  , state(false)
  {
  }

  typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _sender_type;
  std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  sender;

  typedef uint8_t _state_type;
  uint8_t state;


  typedef boost::shared_ptr< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BaseStopRequest
typedef  ::qbo_arduqbo::BaseStopRequest_<std::allocator<void> > BaseStopRequest;

typedef boost::shared_ptr< ::qbo_arduqbo::BaseStopRequest> BaseStopRequestPtr;
typedef boost::shared_ptr< ::qbo_arduqbo::BaseStopRequest const> BaseStopRequestConstPtr;



template <class ContainerAllocator>
struct BaseStopResponse_ {
  typedef BaseStopResponse_<ContainerAllocator> Type;

  BaseStopResponse_()
  {
  }

  BaseStopResponse_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::qbo_arduqbo::BaseStopResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::qbo_arduqbo::BaseStopResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct BaseStopResponse
typedef  ::qbo_arduqbo::BaseStopResponse_<std::allocator<void> > BaseStopResponse;

typedef boost::shared_ptr< ::qbo_arduqbo::BaseStopResponse> BaseStopResponsePtr;
typedef boost::shared_ptr< ::qbo_arduqbo::BaseStopResponse const> BaseStopResponseConstPtr;


struct BaseStop
{

typedef BaseStopRequest Request;
typedef BaseStopResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct BaseStop
} // namespace qbo_arduqbo

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "adc1836ec05769e51272f3bf2b237d1d";
  }

  static const char* value(const  ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xadc1836ec05769e5ULL;
  static const uint64_t static_value2 = 0x1272f3bf2b237d1dULL;
};

template<class ContainerAllocator>
struct DataType< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "qbo_arduqbo/BaseStopRequest";
  }

  static const char* value(const  ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "string sender\n\
bool state\n\
\n\
";
  }

  static const char* value(const  ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::qbo_arduqbo::BaseStopResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::qbo_arduqbo::BaseStopResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::qbo_arduqbo::BaseStopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::qbo_arduqbo::BaseStopResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::qbo_arduqbo::BaseStopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "qbo_arduqbo/BaseStopResponse";
  }

  static const char* value(const  ::qbo_arduqbo::BaseStopResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::qbo_arduqbo::BaseStopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
";
  }

  static const char* value(const  ::qbo_arduqbo::BaseStopResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::qbo_arduqbo::BaseStopResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::qbo_arduqbo::BaseStopRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.sender);
    stream.next(m.state);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BaseStopRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::qbo_arduqbo::BaseStopResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct BaseStopResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<qbo_arduqbo::BaseStop> {
  static const char* value() 
  {
    return "adc1836ec05769e51272f3bf2b237d1d";
  }

  static const char* value(const qbo_arduqbo::BaseStop&) { return value(); } 
};

template<>
struct DataType<qbo_arduqbo::BaseStop> {
  static const char* value() 
  {
    return "qbo_arduqbo/BaseStop";
  }

  static const char* value(const qbo_arduqbo::BaseStop&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<qbo_arduqbo::BaseStopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "adc1836ec05769e51272f3bf2b237d1d";
  }

  static const char* value(const qbo_arduqbo::BaseStopRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<qbo_arduqbo::BaseStopRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "qbo_arduqbo/BaseStop";
  }

  static const char* value(const qbo_arduqbo::BaseStopRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<qbo_arduqbo::BaseStopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "adc1836ec05769e51272f3bf2b237d1d";
  }

  static const char* value(const qbo_arduqbo::BaseStopResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<qbo_arduqbo::BaseStopResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "qbo_arduqbo/BaseStop";
  }

  static const char* value(const qbo_arduqbo::BaseStopResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // QBO_ARDUQBO_SERVICE_BASESTOP_H

